### ISSUE TITLE
Can't convert example code

### ISSUE THREAD

**Issue by lyneca** [googlesamples/md2googleslides#13]
Hi! I'm unable to convert the example documents given to a gSlide. It appears to be something to do with the parser (at least, that's where the error is). I installed via `npm`.

Markdown I wrote:
```
---

# Title!
## Example!
```

Error I got:
```
lyneca at lynux in ~/Documents
$ md2gslides git.md
Unable to generate slides: TypeError: Cannot read property 'references' of undefined
    at Array.link (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/rules_inline/link.js:101:25)
    at ParserInline.tokenize (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_inline.js:135:22)
    at ParserInline.parse (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_inline.js:163:8)
    at Array.inline (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/rules_core/inline.js:10:23)
    at Core.process (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/index.js:523:13)
    at parseMarkdown (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/lib/extract_slides.js:77:19)
    at extractSlides (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/lib/extract_slides.js:56:18)
    at SlideGenerator.generateFromMarkdown (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/lib/slide_generator.js:86:27)
    at generateSlides (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/bin/md2gslides.js:177:27)
    at tryCallOne (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:37:12)
    at /home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:123:15
    at flush (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
TypeError: Cannot read property 'references' of undefined
    at Array.link (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/rules_inline/link.js:101:25)
    at ParserInline.tokenize (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_inline.js:135:22)
    at ParserInline.parse (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_inline.js:163:8)
    at Array.inline (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/rules_core/inline.js:10:23)
    at Core.process (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/markdown-it/lib/index.js:523:13)
    at parseMarkdown (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/lib/extract_slides.js:77:19)
    at extractSlides (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/lib/extract_slides.js:56:18)
    at SlideGenerator.generateFromMarkdown (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/lib/slide_generator.js:86:27)
    at generateSlides (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/bin/md2gslides.js:177:27)
    at tryCallOne (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:37:12)
    at /home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:123:15
    at flush (/home/lyneca/.nvm/versions/node/v8.2.1/lib/node_modules/md2gslides/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
{}
```

**Comment by lyneca** [comment]
Nevermind, error was not to do with your code.

**Comment by sahilkhosla** [comment]
what was the issue?
