### ISSUE TITLE
Timeout, unable to generate slides

### ISSUE THREAD

**Issue by mattwilmott** [googlesamples/md2googleslides#14]
I've been able to generate slides previously but recently it's been timing out. The app is still authenticated and an empty presentation is created so I don't see an issue there. 

Is there a setting or modification I can make to extend the timeout and/or enable debug logging?

```
md2gslides -u redacted@example.com -t TestPresentation1 -e -n example.md
Unable to generate slides: { Error: ETIMEDOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/md2gslides/node_modules/request/request.js:759:15)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5) code: 'ETIMEDOUT', connect: false }
Error: ETIMEDOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/md2gslides/node_modules/request/request.js:759:15)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
{
  "code": "ETIMEDOUT",
  "connect": false
}
```

Note, this was trying to generate a presentation based on the example.md in the examples/ folder. It worked previously as mentioned so there seems to be something else at fault here.

**Comment by wyojustin** [comment]
I'm super excited to find md2gslides!  Thanks.  I just installed and am experiencing the exact same behavior.  So close I can taste it!

**Comment by wyojustin** [comment]
Not sure what fixed it, but I tried the gslides Python API quickstart (which worked), now md2gslides works too.

**Comment by sqrrrl** [comment]
Likely was a transient issue on the API side of things. Closing for now.
